KMOD = ldev

SRCS = opt_cam.h ldev_geom.c
#SRCS = ldev_bsd.c

QUADSTOR_ROOT := /quadstor/quadstor/
CFLAGS = -I. -DFREEBSD
CFLAGS += -O2
#CFLAGS += -g
#DEBUG_FLAGS = -g
#CFLAGS += -DENABLE_STATS

.include <bsd.kmod.mk>
