#!/bin/sh
#
# QUADStor init script 
# chkconfig: 345 84 16
# description: QUADStor Data Protection 
#

# PROVIDE: quadstor
# REQUIRE: DAEMON HOSTNAME mountcritlocal NETWORK
# BEFORE: nfsd
# KEYWORD: nojail shutdown

. /etc/rc.subr
name="quadstor"
start_cmd="quadstor_start"
stop_cmd="quadstor_stop"
status_cmd="quadstor_status"
rcvar=`set_rcvar`

unload_module() {
	/sbin/kldunload $1 > /dev/null 2>&1
	modpresent=`/sbin/kldstat | grep $1`
	tries="0"
	while [ "$modpresent" != "" ]; do
		sleep .1
		/sbin/kldunload $1 > /dev/null 2>&1
		if [ "$tries" = "50" ]; then
			break
		fi
		tries=`expr $tries + 1`
		modpresent=`/sbin/kldstat | grep $1`
	done
}

kill_prog() {
	pkill -f $1
	progpid=`/quadstor/bin/pidof $1 2> /dev/null`
	tries="0"
	while [ "$progpid" != "" ]; do
		sleep .1
		if [ "$tries" = "50" ]; then
			break
		fi
		tries=`expr $tries + 1`
		progpid=`/quadstor/bin/pidof $1 2> /dev/null`
	done
}

quadstor_stop() {
	if [ -f /quadstor/quadstor.lock ]; then
		echo "Waiting 60 seconds for lock"
		sleep 60
	fi

	touch /quadstor/quadstor.lock

	/quadstor/bin/ietadm --op delete >/dev/null 2>/dev/null
	kill_prog "/quadstor/sbin/ietd"

	echo -n $"Stopping $prog: "
	/quadstor/bin/scctl -u > /dev/null 2>&1

	pkill mdaemon
	rm -f /quadstor/.mdaemon

	/quadstor/pgsql/etc/pgsql stop

	unload_module "iscsit" > /dev/null 2>&1
	unload_module "ldev" > /dev/null 2>&1
	unload_module "coredev" > /dev/null 2>&1
	rm -f /quadstor/tmp/.quadstortl.* > /dev/null 2>&1
	rm -f /quadstor/quadstor.lock
}

check_error() {
	if [ "$?" != "0" ]; then
		echo "$1"
		rm -f /quadstor/quadstor.lock
		quadstor_stop
		exit 1
	fi
}

quadstor_start() {

	if [ -f /quadstor/quadstor.lock ]; then
		sleep 60
	fi

	mdaemonpid=`/quadstor/bin/pidof /quadstor/sbin/mdaemon 2> /dev/null`
	if [ "$mdaemonpid" != "" ]; then
		echo "QUADStor Daemon already running..."
		exit 1
	fi
	
        echo -n $"Starting $prog: "

	mkdir -p /quadstor/tmp
	chmod 777 /quadstor/tmp

	touch /quadstor/quadstor.lock
	if [ -f /tmp/.s.PGSQL.9988 -o -f /tmp/.s.PGSQL.9988.lock ]; then
		/quadstor/pgsql/etc/pgsql stop > /dev/null 2>&1
	fi

	/quadstor/pgsql/etc/pgsql start
	check_error "Cannot start database"

	/sbin/kldload /quadstor/lib/modules/coredev.ko > /dev/null 2>&1
	check_error "Failed to insert core module"

	/sbin/kldload /quadstor/lib/modules/ldev.ko > /dev/null 2>&1 
	check_error "Failed to insert ldev module"

	if [ -f /quadstor/lib/modules/iscsit.ko ]; then
		/sbin/kldload /quadstor/lib/modules/iscsit.ko > /dev/null 2>&1
		check_error "Failed to insert iscsi target module"
		daemon /quadstor/sbin/ietd
	fi

	export PATH=$PATH:/quadstor/bin
	rm -f /quadstor/.mdaemon
	/quadstor/sbin/mdaemon > /dev/null 2>&1
	check_error "Cannot start master daemon"

	sleep 5
	/quadstor/bin/scctl -l > /dev/null 2>&1
	rm -f /quadstor/quadstor.lock
}

quadstor_status() {
	mdaemonpid=`/quadstor/bin/pidof /quadstor/sbin/mdaemon 2> /dev/null`
	if [ "${mdaemonpid}" != "" ] ; then 
		echo "QUADStor daemon is running..."
		exit 1
	else
		echo "QUADStor daemon is stopped"
		exit 1
	fi
	
}

load_rc_config $name

: ${quadstor_enable:="NO"}

run_rc_command "$1"

