ALTER TABLE ISCSICONF RENAME COLUMN UNAME TO INCOMINGUSER;
ALTER TABLE ISCSICONF RENAME COLUMN PASSWD TO INCOMINGPASSWD;
ALTER TABLE ISCSICONF DROP COLUMN NOAUTH;
ALTER TABLE ISCSICONF ADD COLUMN OUTGOINGUSER VARCHAR(40);
ALTER TABLE ISCSICONF ADD COLUMN OUTGOINGPASSWD VARCHAR(40);
ALTER TABLE ISCSICONF ADD COLUMN MAXCONNECTIONS INT default 1;
ALTER TABLE ISCSICONF ADD COLUMN MAXSESSIONS INT default 0;
ALTER TABLE ISCSICONF ADD COLUMN INITIALR2T INT default 0;
ALTER TABLE ISCSICONF ADD COLUMN MAXRECVDATASEGMENTLENGTH INT default 65536;
ALTER TABLE ISCSICONF ADD COLUMN MAXXMITDATASEGMENTLENGTH INT default 65536;
ALTER TABLE ISCSICONF ADD COLUMN MAXBURSTLENGTH INT default 262144;
ALTER TABLE ISCSICONF ADD COLUMN FIRSTBURSTLENGTH INT default 65536;
ALTER TABLE ISCSICONF ADD COLUMN NOPINTERVAL INT default 0;
ALTER TABLE ISCSICONF ADD COLUMN NOPTIMEOUT INT default 0;
ALTER TABLE ISCSICONF ADD COLUMN IQN VARCHAR(256);

CREATE TABLE STORAGEGROUP (
	NAME VARCHAR(40) default NULL,
	DEDUPEMETA INT default 0,
	LOGDATA INT default 0,
	GROUPID SERIAL UNIQUE
);

ALTER SEQUENCE storagegroup_groupid_seq MAXVALUE 255 MINVALUE 1 CYCLE;

ALTER TABLE TDISK ADD COLUMN GROUPID INT default 0;

CREATE TABLE MIRRORCHECK (
	MIRRORHOST VARCHAR(40) default NULL,
	CHECKTYPE INT default 0,
	CHECKVALUE VARCHAR(512) default NULL
);

CREATE TABLE FCCONFIG (
	WWPN VARCHAR(40) default NULL,
	TDISKID INT default NULL,
	RULE INT default 0
);

ALTER TABLE FCCONFIG ADD COLUMN WWPN1 VARCHAR(40) default NULL;
